# Generated by Django 5.1.6 on 2025-02-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchanges", "0002_exchange_created_at_exchange_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchange",
            name="state",
            field=models.CharField(
                choices=[("D", "done"), ("P", "pending"), ("C", "cancelled")],
                default="P",
                max_length=1,
            ),
        ),
    ]
